### ISSUE TITLE
知乎不是法外之地但是还有stackexchange.jpg

### ISSUE THREAD

**Issue by WEGFan** [USTC-Hackergame/hackergame2020-writeups#12]
昨天搜 oblivious transfer crack 搜到的 2333
https://crypto.stackexchange.com/questions/85973/1-2-oblivious-transfer-can-the-recepient-obtain-both-secrets-by-manipulating-v
![screenshot-crypto stackexchange com-2020 11 07-14_29_36](https://user-images.githubusercontent.com/7558201/98433946-33f2c280-2106-11eb-9884-23c395c6faef.png)

**Comment by HarukaMa** [comment]
poncho 还是 crypto 版资深成员了23333
不知道 crypto 版和 infosec 版有没有往届各种题的提问……
