### ISSUE TITLE
Flag 计算机官方题解中的问题

### ISSUE THREAD

**Issue by HarukaMa** [USTC-Hackergame/hackergame2020-writeups#45]
看一直没修，还是开个 issue 提一下。

官方题解中提到 IDA 识别字符串：

> 逆向的核心过程就是明白程序干了哪些事情，橙色的操作数代表着地址，我们将鼠标悬停在上面，然后右键把它类型转换一下。
> [图片]
> IDA 就能识别字符串了。

但在此题上下文甚至提供的截图中，这个做法是有问题的：由于段寄存器指向的内存位置不同，IDA 无法一直正确识别一个数字具体引用的位置；此题中 DS 和 SS 的差值就会导致直接在 IDA 中转换内存引用会产生不正确的结果。（甚至截图里直接引用的是一个“字符串+20h“，显然是不正确的。）

我的题解里描述了至少是本题上下文中的具体原理。

**Comment by lyciumlee** [comment]
这两天去被各位 dalao 吊着锤完了。现在修好了
